### ISSUE TITLE
Style Issue: Infobox wird angezeigt, obwohl leer

### ISSUE THREAD

**Issue by JFD23** [virtUOS/studip-meeting#100]
<img width="787" alt="Bildschirmfoto 2020-06-11 um 11 34 02" src="https://user-images.githubusercontent.com/29626127/84370976-49a4a000-abd9-11ea-9bb1-0f56eeda2e5d.png">

**Comment by JFD23** [comment]
mhh ich überdenke gerade meinen Issue Titel. Eigentlich müsste es sein: Infobox gar nicht erst anzeigen, wenn leer ;-)

**Comment by ferishili** [comment]
@JFD23, is it possible to give me hints on how to reproduce it.

**Comment by JFD23** [comment]
Hi,
I am on vacation. 
It’s possible that this has been a cache issue after updating the plugin. 
 I try And write again next week
