### ISSUE TITLE
Alte Aufzeichnungen nach Update nicht sichtbar

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/studip-meeting#101]
War vorher Aufzeichnung erlaubt ist nach einem Update auf die neueste Version keine Aufzeichnung mehr sichtbar.
Problem ist, dass bei allen einzelnen Räumen record=false eingestellt ist.

Eventuell sollte es die Möglichkeit geben, bei den Admin-Einstellungen einmal bei allen Räumen record=true zu setzen.

**Comment by ferishili** [comment]
I would need more described explanation as it is confusing where the issue points to, are we talking about config or features?

**Comment by noackorama** [comment]
The old recordings are not shown if the features column does not contain a "record" entry at all. If there is "record":"false" old recordings are shown.
