### ISSUE TITLE
Zusätzliche Funktionen werden beim Anlegen eines neuen Raums nicht übernommen

### ISSUE THREAD

**Issue by mgieseki** [virtUOS/studip-meeting#107]
Beim Anlegen eines neuen Meetings werden die unter "Zusätzliche Funktionen" vorgenommenen Einstellungen nicht übernommen. Wenn man sie bei einem bereits vorhandenen Raum ändert, funktioniert es.

**Comment by ferishili** [comment]
@mgieseki, I would like to ask you to check this issue again and if it still exists, give me more detailed info.

**Comment by mgieseki** [comment]
Hi Farbod, thanks for the feedback and for fixing this issue. The settings are now correctly saved when creating a new meeting room.
