### ISSUE TITLE
Opencast Metadata

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-meeting#111]
Können wir `opencast-series-id` durch `opencast-isPartOf` ersetzen

**Comment by Arnei** [comment]
Die Idee hinter dieser Änderung ist eine einheitliche Definition für Metadaten zu schaffen, die dann gleichermaßen von anderen LMS-Plugins genutzt werden kann:
https://github.com/elan-ev/opencast-bigbluebutton-integration/blob/master/README.md

**Comment by ferishili** [comment]
Should it be changed to `opencast-dc-isPartOf` or `opencast-isPartOf`?

**Comment by Arnei** [comment]
It should be changed to `opencast-dc-isPartOf`
