### ISSUE TITLE
Pre-upload Slides

### ISSUE THREAD

**Issue by ferishili** [virtUOS/studip-meeting#120]
Slides must be uploaded to the session meeting automatically!

**Comment by tgloeggl** [comment]
Ein-Ordner-Loesung: BBB-Upload-Ordner fuer Slides, wird immer hochgeladen, Dozent muss Aenderungen fuer neue Meetings dort vornehmen und aufraeumen

**Comment by tgloeggl** [comment]
https://github.com/virtUOS/studip-meeting/commit/54a88b42fab39a058bd5812879418b68859d70fb
