### ISSUE TITLE
Feature: Limit for max participants per server

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [virtUOS/studip-meeting#121]
In Hannover we need a limit for max participants on a per server basis to ensure our server-limits are not hit. Therefore an additional column is needed in settings menu to configure the limit per server. Also when creating a room, the input field for max participants needs to be limited by the value of the selected server. Finally the request has to be validated. 

**View in settings menu could look like this:**

![image](https://user-images.githubusercontent.com/53210931/91533718-a5e1ab00-e910-11ea-9dd1-8735ffc611e5.png)

**View in room creation could look like this:**

![image](https://user-images.githubusercontent.com/53210931/91533813-d1fd2c00-e910-11ea-8008-f0567910cb72.png)

**Comment by schuettloeffel-elsa** [comment]
I already startet implementation, if we agree on that issue, I can make a pull-request later.

**Comment by ferishili** [comment]
That looks good to me, however @tgloeggl 's decision is needed here as well.

**Comment by ferishili** [comment]
> I already startet implementation, if we agree on that issue, I can make a pull-request later.

Please make the PR so we can follow up with feature.
