### ISSUE TITLE
Namensabfrage beim Einladungslink

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/studip-meeting#124]
Der Einladungslink soll nicht mehr direkt auf BBB zeigen sondern über Stud.IP umgeleitet werde um dort einen Namen eingeben zu können vor der Weiterleitung zur VK.

**Comment by tgloeggl** [comment]
related: #158, #150

**Comment by noackorama** [comment]
ich bin hier gerade dran. Das müsste in jedem Fall auch berücksichtigen wenn wie in #163 geschrieben nicht-Moderatoren den Raum nicht "öffnen" dürfen.

**Comment by Superjamp** [comment]
Hi, die migration 26 funktioniert für eine fresh insalltion des Plugins leider nicht. (Stud.IP 4.6)

> Call to a member function getPluginId() on null

Leider kann dieses Plugin noch nicht gefunden werden, da es noch nicht in der DB steht und erst nachdem die das DBSchema erstellt wurde hinzugefügt wird. (siehe app/models/plugin_administration.php:123-126)

Habt ihr dafür eine passende Lösung? @noackorama

https://github.com/virtUOS/studip-meeting/blob/250544f8ab360f6d5c9cc57bb31bcf6e413d2cbf/migrations/026_add_invitations_links.php#L19-L20

**Comment by tgloeggl** [comment]
siehe #190
