### ISSUE TITLE
Videokonferenz im gleichen Fenster öffnen

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-meeting#125]
Videokonferenzen werden momentan in einem neuen Fenster gestartet. Verlasse ich die Konferenz oder wird diese beendet, lande ich wieder an der gleichen Stelle in Stud.IP. Damit habe ich dann aber die gleiche Stelle in Stud.IP zweimal auf. Das ist verwirrend. Da es den Rückkehrmechanismus gibt wäre ein öffnen der Konferenz im selben Fenster sinnvoll.

**Comment by JFD23** [comment]
Ja und nein ;-)
Verwirrend, wenn am Schluss zwei Tabs mit Stud.IP offen sind = ja.
Unpraktisch während der Sitzung aber, wenn Materialien aus dem Kurs benötigt werden. Z.B. zeigt bei uns eine Dozentin Videos, die im Dateibereich der Stud.IP Veranstaltung liegen.
