### ISSUE TITLE
UI Problem with contents in the header

### ISSUE THREAD

**Issue by ferishili** [virtUOS/studip-meeting#129]
Header will expand to 3 - 4 lines if the title is long, therefore displaying extra info in the header does not looks good. 
Suggestion by Cornelis: nothing except title/header should be displayed in the header! the rest should be in content part.
<img width="518" alt="Bildschirmfoto 2020-10-08 um 11 31 57" src="https://user-images.githubusercontent.com/53179227/95445377-3fb06500-095f-11eb-8a2a-82d2639d6f69.png">

**Comment by tgloeggl** [comment]
- [ ] "2 Teilnehmende aktiv" in den Content-Bereich verschieben
- [ ] Titel aggressiver kürzen
