### ISSUE TITLE
Dialog ist nicht scrollbar

### ISSUE THREAD

**Issue by Davka** [virtUOS/studip-meeting#130]
<img width="857" alt="Bildschirmfoto 2020-10-09 um 11 13 20" src="https://user-images.githubusercontent.com/1117697/95565740-e7419c00-0a20-11eb-983c-6bd97fd17606.png">

**Comment by Davka** [comment]
Die Einstellungsseite ragt nach unten raus

MACBook 13 Zoll Retina

**Comment by ferishili** [comment]
It has been taken care of in #133
