### ISSUE TITLE
Sprachauswahl über Stud.IP

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/studip-meeting#14]
Anwender an der UOL die internationale Videokonferenzen durchführen, wünschen sich, dass man die AdobeConnect-Oberfläche auch auf Englisch umstellen kann.
Laut Antwort vom DFN:
(...Wenn Sie die Meetings über Stud.IP erstellen, dann müssen Sie die Meetingeigenschaften auch darüber einstellen. Falls Stud.IP keine Sprachauswahl unterstützt ist dies also auch nicht möglich....)

ist es prinzipiell möglich müsste aber übers Plugin gesteuert werden.
Kannst du (Till) bitte mal den Aufwand abschätzen, ob man das nicht ins Plugin integrieren könnte.

**Comment by tgloeggl** [comment]
Wir machen das abhängig von der Nutzersprache, sofern die DFN-API das hergibt.
