### ISSUE TITLE
Meeting-Dauer wird nicht korrekt übermittelt

### ISSUE THREAD

**Issue by Davka** [virtUOS/studip-meeting#142]
Eingestellt waren 120 Minuten, das Meeting wurde aber nach 90 Minuten beendet.

**Comment by rrolf** [comment]
Ich hatte von einem Lehrenden einen ähnlichen Bericht (60 Minuten eingestellt / 30 Minuten Dauer), konnte dass aber nicht verifizieren. Und der Lehrende war sich dann auch nicht sicher ob nicht Studierende das Meeting viel früher betreten hatten

**Comment by tgloeggl** [comment]
Lösung für dieses Problem ist nun die Lobby, d.h. ein/e Lehrende/r konfiguriert den Raum so, dass nur Moderatoren (Tutoren/Dozenten) die Konferenz starten können, dann startet der Timer auch erst, wenn der Lehrende den Raum betritt.
