### ISSUE TITLE
Kontenmigration / Löschen von Lehrenden

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/studip-meeting#145]
Wenn man als Lehrender einen BBB-Raum anlegt und anschließend wird der Lehrende gelöscht (also nicht nur in der Veranstaltung sondern auch im System) oder über einer Kontenmigration,  dann hat man keine Chance mehr über die GUI in dieser Verstanstaltung neue Räume anzulegen, es kommt immer nur eine Fehlermeldung:

Hier wäre es besser, wenn die user_id nicht mehr existiert, diese Räume in dieser Veranstaltung ausblenden oder für die Kontenmigration  bzw. UserDelete eine Notification anzubieten.

**Comment by tleilax** [comment]
Für die Kontenmigration gibt es schon die Notification `UserDidMigrate($old_id, $new_id)`.
