### ISSUE TITLE
Option das Lehrende das Meeting starten

### ISSUE THREAD

**Issue by rrolf** [virtUOS/studip-meeting#149]
In Greenlight gibt es die Option, dass "jeder Teilnehmer kann die Konferenz starten". In Stud.IP kann immer jeder Teilnehmer das Meeting starten. 

In Veranstaltungen mit einem Teilnehmer oder Zeitlimit kann das aber zu Problemen führen. Der Lehrende kann das Meeting nicht mehr betreten oder die Zeit ist vor dem geplanten Ende abgelaufen.
Es wäre also gut wenn erst wenn Lehrende das Meeting betreten haben die anderen Teilnehmenden auch eingelassen werden.

**Comment by tgloeggl** [comment]
related #163
