### ISSUE TITLE
Anklicken von Einladungslinks in Mails klappt nicht immer

### ISSUE THREAD

**Issue by rrolf** [virtUOS/studip-meeting#150]
Ich hatte mit den Einladungslinks ein wenig Probleme. In einigen Mailprogrammen hatte es nicht geklappt die einfach anzuklicken. Wenn man sie markierte und Kopierte funktionierte es aber. 

Ich hatte den Eindruck, dass das Problem vor allem an den Umlauten in meinem Namen liegt. Einem Kollegen der auch einen Umlaut im Namen hat ging es ähnlich. Vielleicht kann man in einem ersten Schritt non-ASCII Zeichen ersetzen?

**Comment by ferishili** [comment]
@rrolf, currently the invitation link to send to the guests will land on the StudIP in order to ask the name, then it redirects to the BBB. In this case, the issue is not valid anymore, however I put front-back sonderzeichen converter in order to make sure that the umlauts are converted.
