### ISSUE TITLE
Einladungslink gibt missverständliche Fehlermeldung, wenn man den anklickt, ohne dass das Meeting schon läuft

### ISSUE THREAD

**Issue by rrolf** [virtUOS/studip-meeting#151]
Wenn man einen Einladungslink anklickt, ohne dass das Meeting schon aktiv ist, gibt es nur eine Missverständliche XML-Fehlermeldung vom Scalite. Nutzer sind dadurch arg verunsichert. 

Gibt es irgendeine Chance:
- dass der Gast das Meeting eröffnet?
- der Gast eine Warteseite sieht, von der er dann weitergeleitet wird?

**Comment by tgloeggl** [comment]
related: #124, #163
