### ISSUE TITLE
Lobby für nicht gestartete Meetings

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/studip-meeting#163]
Es soll für Lehrende die Möglichkeit geben, Meetings erst zu starten, wenn ein Lehrender / Moderator das Meeting betritt. Das geht von BBB aus nicht, das wäre dann eine Lösung innerhalb Stud.IPs.

- [ ] Option: Lehrender startet das Meetings (es interessiert an dieser Stelle nur die Stud.IP Rolle)
- [ ] Studierende landen in einer Art Lobby, wo sie darauf warten, dass das Meeting gestartet wird

siehe auch #124, das ist eventuell im selben Kontext angesiedelt.

**Comment by noackorama** [comment]
Hast du schon eine Vorstellung, wie der Lehrende das "starten" soll? Oder soll es Öffnungszeiten geben?
