### ISSUE TITLE
Loadblancing

### ISSUE THREAD

**Issue by Davka** [virtUOS/studip-meeting#165]
Aktuell haben viele Betreiber einen Scalelite-LB in Meetings eingestellt. 

Leider trifft Scalelite nicht immer die Besten Entscheidungen, sodass u.U. zwei Meetings der Größenordnung > 250 TN auf einen BBB-Server gepackt werden. 

In Meetings kann man mehrere Server hinterlegen, sodass man hier ansetzen könnte und ein eigenes simples LoadBalancing auf Basis der VA-TN und aktueller Auslastung bauen könnte.

Idee wäre, dass alle Server, die zur Verfügung stehen separat in der Admin GUI gespeichert werden.
Beim Start des Meetings müsste man ermitteln, welcher Server am Besten geeignet ist und das Meeting auf dem Server starten. Damit nachfolgende TN den Weg zum Meeting finden, müsste man zwischenspeichern, dass das Meeting aktuell auf Server X läuft.

Konkretes Beispiel wäre:

- VA 1 beginnt 16 Uhr und hat 260 TN in Stud.IP angemeldet
- VA 2 beginnt 17 Uhr und hat 230 TN in Stud.IP angemeldet

Aktuell kann es passieren, dass beide auf Server 1 landen. Ideal wäre es, wenn beide Veranstaltungen auf verschiedenen Servern laufen.

**Comment by tgloeggl** [comment]
Wir hatten uns explizit entschieden, kein Load-Balancing ins Plugin selbst mit reinzubringen, da die Komplexität zu groß ist.
Offenbar schafft ja nicht mal das dafür dedizierte scalelite das immer zuverlässig. ;)

Auf jeden Fall sollte direkt bei scalelite angesetzt werden, falls es dort Probleme mit dem Load-Balancing gibt. Vermutlich werden diese Problem dort auch in zukünftigen Versionen behoben werden.
