### ISSUE TITLE
Räume müssen einen Namen haben

### ISSUE THREAD

**Issue by rrolf** [virtUOS/studip-meeting#170]
Anscheinend ist es möglich Räume ohne einen Namen anzulegen. Bei diesen Räumen schlagen die Aufzeichnungen fehl.

**Comment by ferishili** [comment]
@rrolf Would you please describe how to reproduce this issue (create a room without name). It is not possible for me!

**Comment by tgloeggl** [comment]
Das muss ein anderes Problem gewesen sein, auf jeden Fall wird auch serverseitig überprüft, ob der Raum einen Namen hat.
