### ISSUE TITLE
Waring/Deprecated Meeting-Plugin Version 2.42

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/studip-meeting#172]
`studip-4.3/public/plugins_packages/elan-ev/MeetingPlugin/app/models/Driver.php on line 70 Deprecated: Non-static method ElanEv\Driver\BigBlueButton::getCreateFeatures() should not be called statically in /mnt/data/devel13/studip-4.3/public/plugins_packages/elan-ev/MeetingPlugin/app/models/Driver.php on line 70 Deprecated: 
Non-static method ElanEv\Driver\BigBlueButton::getRecordFeature() should not be called statically in /studip-4.3/public/plugins_packages/elan-ev/MeetingPlugin/app/models/Driver.php on line 75 Deprecated: Non-static method ElanEv\Driver\DfnVc::getCreateFeatures() should not be called statically in /mnt/data/devel13/studip-4.3/public/plugins_packages/elan-ev/MeetingPlugin/app/models/Driver.php on line 70`

**Comment by ferishili** [comment]
fixed & merged in https://github.com/virtUOS/studip-meeting/commit/dba277274d3ad6ce8cc8722623ae56d202d20a4c
