### ISSUE TITLE
Fatal Error bei Teilnahme / Slim Application Error (Plugin 2.42, Stud.IP < 4.2 oder > 4.5) 

### ISSUE THREAD

**Issue by noackorama** [virtUOS/studip-meeting#175]
In 2.42 kann man nicht an einem Meeting teilnehmen, wenn die Veranstaltung einen laufenden Termin hat. Es wird versucht automatisch Slides hochzuladen, in Versionen vor 4.2 scheitert das mit
 Slim Application Error:\nType: Error\nMessage: Call to undefined method CourseDate::getAccessibleFolderFiles()\nFile: /webapps/studip-4.1/public/plugins_packages/elan-ev/MeetingPlugin/Driver/BigBlueButton.php\nLine: 412

In 4.6 scheitert der folgende Quellcode, da dort auf file->storage zugegriffen wird, das es nicht mehr gibt.

**Comment by tgloeggl** [comment]
Für Stud.IP >4.5 ist es gefixt, siehe #207 
Wir untersützen Stud.IP <4.2 nicht mehr, als Workaround kann man diese Funktion als root in den Einstellungen abschalten.
