### ISSUE TITLE
Typo Gästelink und Linkbezeichnung 

### ISSUE THREAD

**Issue by JFD23** [virtUOS/studip-meeting#196]
Im letzten Schritt der Gästelink erstellung müsste der Button "Einladungslink kopieren" heißen und nicht "Einladungslink erstellen", da man dies bis dahin schon getan hat. Es fehlen die ä Pünktchen bei Standard-Gastename. Siehe Screenshot

![einladungslink](https://user-images.githubusercontent.com/29626127/109474930-5160e900-7a75-11eb-8e82-21eff1a4978d.png)

**Comment by ferishili** [comment]
Typo ist in https://github.com/virtUOS/studip-meeting/commit/c94b38d38866078442a66acc3f59a2e0c5d90aa4 gefixt worden.
