### ISSUE TITLE
Reiter-Ebene verschwindet

### ISSUE THREAD

**Issue by tleilax** [virtUOS/studip-meeting#21]
> Wenn man im Meeting-Plugin ein zuvor angelegtes Meeting löscht, wird anschließend die zweite Menüleiste (ehemals "Reiter") oben nicht mehr angezeigt. D.h. man muss erst wieder auf "Veranstaltungen" klicken und die jeweilige Veranstaltung auswählen, in der man im Meeting-Plugin ein Meeting gelöscht hatte.

Aus dem Stud.IP-Trac übernommen: https://develop.studip.de/trac/ticket/8669

**Comment by tgloeggl** [comment]
fixed in https://github.com/virtUOS/studip-meeting/commit/7a0f21e16e63c3306c8e951309fa766639e2ea30
