### ISSUE TITLE
PHP version && composer.lock

### ISSUE THREAD

**Issue by ferishili** [virtUOS/studip-meeting#223]
When the composer.lock is not there, it could end up in a composer failure (as experienced: 7.1.0 required --> 7.0.33 installed)
dependencies must be locked at all times, min required PHP version must be checked as well!

**Comment by tgloeggl** [comment]
- [ ] Min Stud.IP version 4.2 
- [ ] Make sure PHP 7.0 is the supported version, lock that version in compser ( https://andy-carter.com/blog/composer-php-platform )
