### ISSUE TITLE
Guest Policy (ASK_MODERATOR) prevents participants to join!

### ISSUE THREAD

**Issue by ferishili** [virtUOS/studip-meeting#225]

**Comment by ferishili** [comment]
According to BBB API desc. guestPolicy has only 3 values (ALWAYS_ACCEPT, ALWAYS_DENY, and ASK_MODERATOR). However, when moderator selects ASK_MODERATOR, every participant must get the permission to join (guest and regular). 
This brings some confusion, and AFAIK there is nothing that can be done in plugin, since it is a logic and a behavior of BBB system itself. 
In this case there should be some notification or some indication to explain this!

**Comment by tgloeggl** [comment]
I guess that we need to rework the presentation of this feature a bit. Currently its named "Zugang via Link". I suggest we do the following to solve this issue:
- [ ]  "Zugang via Link" becomes a Checkbox-Option (ALWAYS_ACCEPT or ALWAYS_DENY)
- [ ] Add another option "Moderatoren vor Teilnehmendenzutritt fragen" (ASK_MODERATOR) <- This option would have precedence over the above two options
- [ ] Only when "Zugang via Link" is enabled, the Button to create a link appears

Any feedback to this idea? Is it feasible?

**Comment by ferishili** [comment]
> Any feedback to this idea? Is it feasible?

Seems fine to me, let's implement it and test if it works all the way through.
