### ISSUE TITLE
Add correct info text to tooltips

### ISSUE THREAD

**Issue by mgieseki** [virtUOS/studip-meeting#232]
Currently, almost all tooltips of the additional configuration options of a meeting room show the following text:
```
Wenn leer, wird die Standardnachricht angezeigt.
Sie können folgende Schlüsselwörter einfügen, die automatisch ersetzt werden:
%% CONFNAME %% (Sitzungsname), %% DIALNUM %% (Sitzungswahlnummer)
```
It would be great if they could be updated to a bit more helpful information on the corresponding options. 😉

**Comment by ferishili** [comment]
Thanks for your advice, the problem is fixed and will be available on the next version.

**Comment by mgieseki** [comment]
Great. Thanks for the immediate fix!
