### ISSUE TITLE
[UI] restricting certain servers for specific seminar/course types could be improved

### ISSUE THREAD

**Issue by crosscodr** [virtUOS/studip-meeting#264]
Hi @ferishili,

I tested the beta feature for restricting certain servers for specific seminar/course types.
Back then, I think the feature was implemented so, that one could not select servers in a course which were not accessible for this course type.
Now in 2.62 one can select unavailable servers and get an error message when trying to save the preferences:
> Der ausgewählte Server ist in diesem Veranstaltungstyp nicht verfügbar.

I think the former behaviour of the plugin was better.
Could you grey-out the non-available servers and put the error-message from above right beside it in the drop down selection menu of the room preferences?

I hope it is clear what I mean :)

**Comment by ferishili** [comment]
Hi @crosscodr,
I will try it out and update the beta-test, will let you know when it is ready.

**Comment by crosscodr** [comment]
I would also suggest to grey-out deactivated servers, with a short remark, instead of letting a user choose such a server and then throw an error-message.

**Comment by crosscodr** [comment]
Nevermind, it was just my fault, having build the plugin in a broken state.
