### ISSUE TITLE
Löschen von Nutzern in Stud.IP

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/studip-meeting#271]
Wenn über die Benutzerverwaltung einen Nutzer löschen will, kommt dieser Fehler:

PHP message: Error: Class 'ElanEv\Model\MeetingCourse' not found in /var/www/studip-4.6/public/plugins_packages/elan-ev/MeetingPlugin/MeetingPlugin.php:351 
Stack trace: 
- #0 /var/www/studip-4.6/lib/classes/NotificationCenter.class.php(127): MeetingPlugin->DeleteMeetingOnUserDelete('UserDidDelete', Object(User), NULL) 
- #1 /var/www/studip-4.6/lib/models/SimpleORMap.class.php(2210): NotificationCenter::postNotification('UserDidDelete', Object(User)) 
- #2 /var/www/studip-4.6/lib/models/SimpleORMap.class.php(2116): SimpleORMap->cbNotificationMapper('after_delete') 
- #3 /var/www/studip-4.6/lib/models/SimpleORMap.class.php

**Comment by ferishili** [comment]
@nimuelle, the new release 2.63 should fix that problem.
Thanks for your feedback
