### ISSUE TITLE
Raumgröße wird nach dem Anlegen häufig vergessen

### ISSUE THREAD

**Issue by Rillke** [virtUOS/studip-meeting#273]
Es gibt Dozenten, die die Räume zu Beginn des Semesters anlegen, wenn noch nicht alle Interessenten eingeschrieben sind. Das Plugin schlägt i.d.R. die Zahl der aktuell Teilnehmenden + X als maximal erlaubte Konferenzteilnehmende vor. Lehrende übersehen das und speichern den Raum.

![image](https://user-images.githubusercontent.com/2311611/122666539-20383000-d1ae-11eb-93db-897a36f09da6.png)

Später schreiben sich mehr Studierende in die Veranstaltung ein.

Beim ersten Meeting können einige Studierende dann wegen Begrenzung der maximalen Teilnehmerzahl in diesem Konferenzraum (nicht Server-Limit) nicht an der Konferenz teilnehmen.

Die folgenden Vorschläge kamen von unserem (hausinternen) Kunden:

* Maximale Teilnehmerzahl immer am Raum anzeigen, so dass alle die Begrenzung sehen und verstehen, warum sie nicht in den Konferenzraum dürfen
* Dem Lehrenden eine Warnung im Konferenzbereich anzeigen, wenn die Zahl der Kursmitglieder die Maximalzahl der Teilnehmenden eines Meetings überschreitet
* Zahl bei Neueinschreibungen in den Kurs automatisch anpassen

**Comment by tgloeggl** [comment]
Nach Rücksprache mit den BBB-Experten wird die Lösung für das Problem wie folgt aussehen:
* Standardmäßig wird die maximale Teilnehmendenzahl auf `0` gesetzt, das soll intern dafür sorgen das als maximale Anzahl das Limit des Servers gesetzt wird
* Nur wenn jemand von Hand dort eine Zahl einträgt, wird diese Zahl verwendet (sofern <= dem Serverlimit des ausgewählten Servers ist)
* Auf der Übersichtsseite wird das jeweilige Limit angezeigt
