### ISSUE TITLE
Kursbasierte "Standardfolie" für BBB Raum

### ISSUE THREAD

**Issue by rrolf** [virtUOS/studip-meeting#278]
Wenn nicht ein Ordner mit Präsentationen für einen BBB Raum definiert wurde, sollte eine Standardpräsentation übergeben werden, die den Namen des Kurses und ähnliches enthält. 

Eine der Motivationen, wäre dass das z.B. in den Aufzeichnungen viel besser wirken würde als die default Folie der Uni.

**Comment by tgloeggl** [comment]
- one could include the seminars news in the presentation
- pdf generation can be easily done in Stud.IP
- the pdf might als be aware of room setiings and include / exclude things based on that

**Comment by tibroc** [comment]
See also #270
