### ISSUE TITLE
Auswahl beim Anlegen eines Raumes, ob auch die Webcam bei BBB in der Aufzeichnung angezeigt werden soll

### ISSUE THREAD

**Issue by rrolf** [virtUOS/studip-meeting#279]
Mit der nächsten Opencast Version kann auch die Webcam aufgezeichnet werden. Ich gehe davon aus, dass viele Lehrende und Studierende das ggf nicht wollen. Dem entsprechend sollte für den Raum hinterlegt sein, ob die Webcam aufgezeichnet werden soll.

**Comment by tgloeggl** [comment]
Es sollte dann einen Warnhinweis geben, wenn die WebCam-Aufyzeichnung eingeschaltet ist, damit Studierende / Personen sich dagegen entscheiden können.

**Comment by ferishili** [comment]
@rrolf, it would be nice to have an Opencast + compatible BBB test instance to work with. In addition, I need a flag or variable name to send to BBB to be consumed by Opencast via metadata (most probably starting with opencast_dc_*).

**Comment by ferishili** [comment]
dependency: https://github.com/elan-ev/opencast-bigbluebutton-integration/pull/36/commits/d13c1db2bbe2d8020f659a8a24fec0d827aa0845
