### ISSUE TITLE
Startseiten Widget mit den nächsten Videokonferenzen

### ISSUE THREAD

**Issue by rrolf** [virtUOS/studip-meeting#281]
Ein Widget für die Stud.IP Startseite wäre wünschenswert, in dem man einen direkten Link zur nächsten anstehenden Videokonferenz sofort angezeigt kriegt, ohne erst den Kurs suchen zu müssen oder ähnliches. 

Wahrscheinlich wäre es auch unabhängig von den Videokonferenzen für Studierende derzeit interessanter den aktuellen und nächsten Kurz schnell finden zu können. Es gibt ja auch noch Live-Streams über Opencast oder das Live-Streaming Plugin oder CliQR etc, was man schnell finden möchte.

**Comment by tgloeggl** [comment]
- [ ] depends on #280
