### ISSUE TITLE
Passwörter und Secrets in Übersichtsseite der Einstellungen sichtbar

### ISSUE THREAD

**Issue by Rillke** [virtUOS/studip-meeting#298]
Passwörter und Secrets sind in Übersichtsseite der Einstellungen sichtbar. Beim Erstellen von Screencasts und Screenshots ist das problematisch und man muss nacharbeiten. Auch, wenn man in einem crowded place Stud.IP administriert, ist das ungünstig.

Erwartetes Verhalten: Passwörter und Secrets werden in der Übersichtsseite entweder durch Platzhalter dargestellt (Bonus: und können bei Bedarf eingeblendet werden) oder gar nicht. (Das mit dem Blur unten ist nur beispielhaft und kein besonders gutes)

<img width="170" alt="Screenshot 2021-08-27 at 11 43 51" src="https://user-images.githubusercontent.com/2311611/131107827-18b3287e-2ca1-4045-b308-73ef5055c315.png">
<img width="182" alt="Screenshot 2021-08-27 at 11 43 45" src="https://user-images.githubusercontent.com/2311611/131107833-1c491da4-b6bb-4cf7-aa8e-a581b2b3811e.png">

**Comment by ferishili** [comment]
see also #299

**Comment by tgloeggl** [comment]
- Besser einfach komplett in der Übersichtstabelle ausblenden
