### ISSUE TITLE
Passwörter und Secrets werden in den Detail-Einstellungen im Klartext angezeigt

### ISSUE THREAD

**Issue by Rillke** [virtUOS/studip-meeting#299]
Passwörter und Secrets werden in den Detail-Einstellungen im Klartext angezeigt. Beim Erstellen von Screencasts und Screenshots ist das problematisch und man muss nacharbeiten. Auch, wenn man in einem crowded place Stud.IP administriert, ist das ungünstig.

<img width="531" alt="Screenshot 2021-08-27 at 11 40 21" src="https://user-images.githubusercontent.com/2311611/131107381-a5e6cccd-1014-444a-8e39-09e1db47d519.png">

Erwartetes Verhalten: Passwörter und Secrets (z.B. der API Key) werden in den Details durch Platzhalter dargestellt (Bonus: und können bei Bedarf eingeblendet werden).

<img width="375" alt="Screenshot 2021-08-27 at 11 46 45" src="https://user-images.githubusercontent.com/2311611/131108177-525e9844-5650-4e86-bf3f-8290df22f5ae.png">

**Comment by tgloeggl** [comment]
- Analog zum Opencast-Plugin zusätzlich noch nur 5 Zeichen anzeigen
