### ISSUE TITLE
Loadbalancing von BBB?

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/studip-meeting#33]
Ist es denkbar, dass durch das Plugin zu realisieren?

**Comment by tgloeggl** [comment]
This should be done by the plugin if at all possible

**Comment by ferishili** [comment]
Based on what I have observed, the closest relevant approach we could take for V2 is to make one at a time distribution. What do you think?

**Comment by tgloeggl** [comment]
It seems that we will not need that anymore, at least nor for UOS. Nonetheless would i like to finish the work on this to give others an easy possibility of simple load balancing.

So, i am thinking of a simple round robin. The first user joining a room decides the server all following users will join.
* Race conditions must be avoided at all costs, or users will end up on different Servers. So, right before a user joins some checks are necessary
* It is necessary to solve the problem on which server to look for the current meeting status - maybe clear the selected server until a user wants to join?

**Comment by tgloeggl** [comment]
After thinking about it, i would even be willing to go back to your solution of selecting a server by hand, if there is more than one. What do you think? Would cirumvent the now unecessary load balancing stuff directly in Stud.IP

**Comment by ferishili** [comment]
Regarding to that, I would say, I agree with that if there is more than one room (Lecturer - Admin) is able to select the server by hand, and regarding to your second last comment, there will be no Race anymore when it has to be done by Lecturer / Admin
