### ISSUE TITLE
Plugin defekt für Einrichtungen

### ISSUE THREAD

**Issue by tleilax** [virtUOS/studip-meeting#34]
Aktiviert man das Plugin in Einrichtungen und erstellt den ersten Raum, so wird in der Tabelle `seminare` ein neuer Eintrag mit der Id der Einrichtung erstellt. Dies bringt Stud.IP dann aus dem Tritt, weil es nicht mehr korrekt erkennen kann, ob der gewählte Kontext eine Veranstaltung oder eine Einrichtung ist.

**Comment by tleilax** [comment]
Hintergrund ist der, dass im Plugin scheinbar nur von Veranstaltungen bzw. Models vom Typ `Course` ausgegangen wird. Auch im Model `Meeting` werden nur verknüpfte Veranstaltungen erfasst. Leider hat dieses Model ein `on_store => store` definiert, weshalb es zu dem oben beschriebenen Phänomen kommt, wenn das Meeting gespeichert wird.

Ein Hotfix für Versionen >= 4.2 ist folgender Code in der Hauptklasse des Plugins, um zu verhindern, dass das Meetingsplugin in einer Einrichtung aktiviert werden kann:

```php
    public function isActivatableForContext(Range $context)              
    {
        return get_class($context) === Course::class;
    }
```

Wünschenswert wäre hier aber eine Anpassung des Plugins, so dass es auch in Einrichtungen zuverlässig aktiviert werden kann. Dafür muss vermutlich an diversen Stellen der Kontext genauer unterschieden werden. Um das genau abschätzen zu können, fehlt mir aber leider der Überblick.

**Comment by tgloeggl** [comment]
Wir bauen den von Jan vorgeschlagenen Fix ein
