### ISSUE TITLE
GUI Tasks

### ISSUE THREAD

**Issue by rlucke** [virtUOS/studip-meeting#340]
- [x] meetingcomponent should have a max-width, I would reccomand twice the size of the sidebar (2 x 270px)
- [x] actions in meeting-item-header schould be in a drop down action menu
- [x] spacing in meeting-item-header is uneven, bottom space is larger than top spacing
- [x] presentation_sildes_section might be pretty long, because teachers may have a lot of files in a folder, max-height and overflow will do the job
- [x] conference-meeting justify-content space-between creates too much space in some resolutions, I recommand flex-start and some margin for the items
- [x] room filter input should be as high as the button next to it, adding the filter icon would create more attention 
- [x] max participants should not be part of the header, put it in details instead

**Comment by ferishili** [comment]
see #388 && #360
