### ISSUE TITLE
Feedback function

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/studip-meeting#342]
The feedback function does not include the users mail address. For convenience purposes this would be useful.

**Comment by ferishili** [comment]
This feature has been implemented before:
see also https://github.com/virtUOS/studip-meeting/issues/274

**Comment by ferishili** [comment]
It is configurable via Admin > System > Meetings konfiguration > Allgemeine Konfiguration > Feedback Absenderadresse
![Screenshot from 2021-11-09 17-15-24](https://user-images.githubusercontent.com/53179227/140962295-158b6872-3227-47fc-b740-665c25a0ebb9.png)
