### ISSUE TITLE
Usability problem with invite link/code for moderator

### ISSUE THREAD

**Issue by asudau** [virtUOS/studip-meeting#344]
the usability is a bit confusing for this feature. What happened to me, when i tested this was the following:  
1. I configured invitation of moderator  
2. I entered a 'Zugangscode' an klicked on the button (Zugangscode generieren)  
3. I got a link but the Code changed  
  
The new code wasn't workung, but the first which I entered manually did.  
  

What happened?  
Entering a code manually and clicking the button 'Zugangscode generieren' are two ways to get a code. The interface implies to enter a code and then click the button to create something.  
Maybe placing the button in the same line might help?  
  
Anyway the button 'Zugangscode generieren' should not do more than what it says. Instead clicking it after entering a code manually creates  a new code AND offers the user a link (which doesn't work with the new code).  

If it only changed the code, the user would need to find and klick the button 'Einladungslink erstellen' and the code wouldn't change.

**Comment by asudau** [comment]
![meetings_moderatorenlink](https://user-images.githubusercontent.com/11834384/141139793-f86e91d7-c3ba-4ee7-b56b-4dfd6b952ef0.PNG)

**Comment by ferishili** [comment]
Final usability decision on this issue would be to make the input read-only, which means that code generation only happens when uses click on the button to generate the code!
