### ISSUE TITLE
Erweiterungsanfrage Aufnahmefunktion

### ISSUE THREAD

**Issue by flausen** [virtUOS/studip-meeting#363]
Hallo,

wäre es möglich das Plugin so zu erweitern, dass die TN im Plugin auswählen können, ob Sie mit einer Aufnahme einverstanden sind, oder nicht. Dieser Haken kann stets durch die TN gesetzt oder entzogen werden.

Bevor der Moderator den Raum betritt wird geprüft, ob alle anwesenden Personen der Aufnahme zugestimmt haben. Falls ja, wird in BBB der Aufnahmebutton angezeigt (die Checkbox im Plugin also gesetzt), falls auch nur eine Person keinen aktiven Haken hat, so wird nicht aufgezeichnet.
Dies verhindert zwar, dass eine in der Veranstaltung abwesende Person für alle die Aufnahme verhindert, aber mir fällt kein besserer Weg ein, wie technisch und vorab die Aufnahmebereitschaft abgefragt werden kann.

**Comment by ferishili** [comment]
see #403

**Comment by ferishili** [comment]
A solution was added and merged in #403
