### ISSUE TITLE
Commit composer.lock

### ISSUE THREAD

**Issue by Rillke** [virtUOS/studip-meeting#366]
Hi,

would it be possible to have the composer lockfile (`composer.lock`) included in this repository for the [reasons outlined on SO](https://stackoverflow.com/a/12896850/2683737)?

**Comment by ferishili** [comment]
Hey, we had that before, but because there are different users with different installations, we decided to have `composer.json` only!

**Comment by Rillke** [comment]
>Hey, we had that before, but because there are different users with different installations

So basically you are saying, they forked the repo, and in order to prevent merge conflicts in their repos when pulling changes from this repo, the lock file is not committed?

This makes it btw. impossible to reproduce the same build as you are creating for the Stud.IP Marketplace. Is suggest but not urge to reconcile.
