### ISSUE TITLE
Slide storage location

### ISSUE THREAD

**Issue by Rillke** [virtUOS/studip-meeting#369]
Hi @ferishili , thanks for implementing the feature #278.

We ran into an issue with the store location. Did you intentionally store the uploaded slides in `/public/plugins_packages/elan-ev/MeetingPlugin/templates/default_slides` ?

We are using multiple PHP-FPM servers through docker containers and now have to build-in the slides into the images in order for them not to be removed when removing the containers and for all PHPs to be available.

If the uploaded default slides and templates remains at the current storage location, we should probably document that.

**Comment by ferishili** [comment]
Hi @Rillke, the first initial concept was only to make it easy for admins as well as plugin itself to get those files. Please describe more about you problem and give me your suggestions where would be the best place to have them?

**Comment by Rillke** [comment]
Our Stud.IP installation contains a directory for user-generated content at `./data/` and below. Not sure how other installations look like. It was a surprise to find user generated content to be stored to the plugin directory. Meanwhile, I mounted new volumes and sync the files through a shared storage so the issue is resolved for us.

As a general note, I would be careful storing user generated content in plugin directories for the following reasons:

1. directories might be write-protected (there is usually no good reason for PHP to write into portions where PHP code is interpreted - except when compromised)
2. multiple PHP servers might be in use and the directory might not be shared between all those PHP servers
3. extra directory contents might not be persistent when the software is baked into images and ephemeral containers

Unrelated to the 3 points above, allowing upload and php execution might allow a studip root (but not server admin) to upload php code through UI and extend their privileges and compromising other portions of code if that's not read-only, even manipulating the log if they wanted to. This plugin should clearly indicate that thread.

**Comment by ferishili** [comment]
The issue was solved in #410
