### ISSUE TITLE
Standard-Folien verwalten - nur BBB oder auch DfnVC und Teams

### ISSUE THREAD

**Issue by Rillke** [virtUOS/studip-meeting#370]
Thanks for implementing #278 and creating an option to configure default slides.

![image](https://user-images.githubusercontent.com/2311611/156775479-5791de4b-f1ee-4ec3-956d-1d66e9fea4d4.png)

Does the default slide option work for any other conferencing system than BBB? If not, are there any plans to do so? If not, might we want to move the button into the BigBlueButton config area?

**Comment by ferishili** [comment]
Hey, the code can be adopted into other drivers if they provide this feature but it was initiated from BBB at the time! I would suggest to have it that way and not to make it driver specific.

**Comment by Rillke** [comment]
Aye. Then it shall be that way.
