### ISSUE TITLE
Feature request: Make automatic recording settings for new BigBlueButton meetings configurable

### ISSUE THREAD

**Issue by s-at-dq** [virtUOS/studip-meeting#374]
The default for new BigBlueButton meetings in Meetings 2.68 is that recordings shall start automatically. This makes it too easy for lecturers to accidently create a meeting with automatic recording enabled, even if they want to start recordings manually or not want any recordings at all.

It would be good to have a global option that can toggle the default setting for automatic recording for new meetings.

**Comment by Rillke** [comment]
See #367

**Comment by ferishili** [comment]
Closed by #367
