### ISSUE TITLE
Fehlender Eintrag "+ Raum hinzufügen"

### ISSUE THREAD

**Issue by Rillke** [virtUOS/studip-meeting#377]
Es fehlt leider die Möglichkeit einen neuen Raum zu erstellen im Stud.IP - wenn vorher noch kein Meetingraum bestand. Das Feld unter “Aktionen” ist leer, bei Veranstaltungen mit bereits bestehenden Räumen gibt es hier den Punkt “+ Raum hinzufügen”

![Clipboard - 14  März 2022 10 47](https://user-images.githubusercontent.com/2311611/158169230-98143810-1202-4907-b359-d96eb6ecf346.png)

Fix: #376

**Comment by ferishili** [comment]
Closed in https://github.com/virtUOS/studip-meeting/pull/376
