### ISSUE TITLE
Dateiordnerauswahl für einen BBB-Raum klappt nur einmal

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/studip-meeting#387]
Ich lege einen BBB-Raum innerhalb einer Veranstaltung an und wähle einen Dateiordner mit 3 PDF's für die "Default-Folie" aus.
Betrete ich den Raum zum ersten Mal, wird mir die erste PDF als Default-Folie angezeigt und die anderen als Auswahl angeboten.

Schließe ich den Raum und gehe danach noch einmal rein. Werden nie wieder die PDF's übertragen bzw. angezeigt.

Der Fehler tritt sowohl in der 2.67 als auch in der 2.68 auf.

**Comment by ferishili** [comment]
Du solltest den Raum **beenden**, oder einfach 2-5 min warten bis der Raum von BBB runtime process entfernt!

**Comment by nimuelle** [comment]
Nein, leider nicht. Wenn ich in einen vorhandenen Raum 24 Stunden später wieder reingehe, funktioniert das auch nicht. Es klappt nur einmal beim Anlegenn. Danach ist es mir nie wieder gelungen.

**Comment by ferishili** [comment]
Hi @nimuelle,
Ich habe mehrmal versucht, dieses Issue zu reproduzieren, aber jedes mal hat es geklappt!
Es wäre super, wenn wir uns in einer VK (für LIVE Demo) treffen könnten!

**Comment by ferishili** [comment]
Bitte schaue einmal diese PR https://github.com/virtUOS/studip-meeting/pull/392 an
