### ISSUE TITLE
Datenschutzhinweis wie im Greenlight

### ISSUE THREAD

**Issue by Davka** [virtUOS/studip-meeting#403]
Beim Betreten des Raumes, soll drauf hingewiesen werden, dass eine Aufzeichnung stattfinden kann.
Der Nutzer muss explizit eine Checkbox anklicken, die dann den Teilnehmenbutton aktiviert

**Comment by ferishili** [comment]
Ich würde es so machen:
1. General config für admins um das Feature aus/einzuschalten
2. Wenn Teilnehmen-Knopf ist gedrückt, ein Confirmation-Dialog (mit Datenschutzhinweis) wird gezeigt um das Feature etwas schöner anzuzeigen

**Comment by ferishili** [comment]
Hi @Davka,
könntest du bitte den PR einaml checken und testen?
Ich warte auf deine Feedback um den PR zu mergen!
