### ISSUE TITLE
Buttontext Einladungslinks vereinheitlichen

### ISSUE THREAD

**Issue by asudau** [virtUOS/studip-meeting#408]
![image](https://user-images.githubusercontent.com/11834384/176882551-b7a10c52-0f13-438e-a13c-a992e757f732.png)

Die Formulierung ist unterschiedlich bei gleicher Funktionalität, bitte vereinheitlichen in:
Einladungslink für Moderierende + Einladungslink für Teilnehmende

**Comment by ferishili** [comment]
The suggested button texts are too long and will break the UI. Therefore, a shorter version of the texts would work better:

The suggested button texts:
![Screenshot from 2022-07-27 14-37-31](https://user-images.githubusercontent.com/53179227/181248759-9a930c11-dcc9-47a3-ab7d-e3dc313955b9.png)


Recommended texts:
![Screenshot from 2022-07-27 14-41-12](https://user-images.githubusercontent.com/53179227/181249156-4aeb386f-9db2-468d-a2f3-87ffefa0de9f.png)
