### ISSUE TITLE
Konferenzen in BBB können über die URL geöffnet werden

### ISSUE THREAD

**Issue by noackorama** [virtUOS/studip-meeting#41]
Getestet mit BBB:
mit joinMeeting/<nr> kann man einen Konferenzraum betreten wenn man kein Teilnehmer ist, wenn man die cid weglässt. Bug oder Feature?

```
diff --git a/app/controllers/index.php b/app/controllers/index.php
index 29d869a..0f06a63 100644
--- a/app/controllers/index.php
+++ b/app/controllers/index.php
@@ -378,7 +378,10 @@ class IndexController extends MeetingsController
         /** @var Seminar_User $user */
         $user = $GLOBALS['user'];
 
-        $meeting = new Meeting($meetingId);
+        $meeting = Meeting::find($meetingId);
+        if (!($meeting && $meeting->courses->find(Context::getId()))) {
+            throw new Trails_Exception(400);
+        }
         $driver = $this->driver_factory->getDriver($meeting->driver);
 
         // ugly hack for BBB

```

**Comment by tgloeggl** [comment]
War mal ein hidden Feature, ist mittlerweile aber als Bug einzustufen und wird behoben!

**Comment by ferishili** [comment]
@noackorama could you please explain a bit on what should be done here!
What I understand is that, it should not check for Course anymore, oder?

**Comment by noackorama** [comment]
No quite the opposite. It should always check if the given meeting is linked to the current course.
