### ISSUE TITLE
Meetings 2.69: Exception on all plugin pages in Stud.IP 5.2

### ISSUE THREAD

**Issue by s-at-dq** [virtUOS/studip-meeting#419]
The localisation methods in the controllers cause exceptions in Stud.IP 5.2. When opening one of the actions of the plugin (/admin or /index), I get an exception because the method "_" does not exist. For example, when I open the plugin page in a course:

```
Typ: RuntimeException
Nachricht: Method _ does not exist
Code: 0
Stack trace:
#$ public/plugins_packages/elan-ev/MeetingPlugin/app/controllers/index.php(104)
#0 public/plugins_packages/elan-ev/MeetingPlugin/app/controllers/index.php(262): IndexController->__call('_', Array)
#1 public/plugins_packages/elan-ev/MeetingPlugin/app/controllers/index.php(144): IndexController->getHelpbarContent('main')
#2 vendor/trails/trails.php(557): IndexController->index_action()
#3 app/controllers/studip_controller.php(116): Trails_Controller->perform('')
```

I tried to use Meetings 2.69 with a modified manifest file (setting studipMaxVersion to 5.2.99) on Stud.IP 5.2.

**Comment by ferishili** [comment]
Hi @s-at-dq 
the problem has been taken care of in #414 and will be released in new version 2.70 soon.

PS: The new version only supports up to Stud.IP v5.1.99
