### ISSUE TITLE
Umlaute im Titel verschwinden

### ISSUE THREAD

**Issue by noackorama** [virtUOS/studip-meeting#50]
Unsere Dozenten habe kleine Fehler im Meetings Plugin gefunden.

Stud.IP Version: 4.4.1

Wenn sich im Titel eines Meetings Umlaute befinden und man den Titel nachträglich ändert 
dann verschwindet alles vom Titel, was nach dem ersten Umlaut im Titel kommt.

Ist der erste Buchstabe im Titel ein Umlaut, verschwindet der komplette Titel.

**Comment by ferishili** [comment]
@noackorama is it possible to attach screenshots?

**Comment by noackorama** [comment]
just remove the obsolete utf8_decode()s
https://github.com/virtUOS/studip-meeting/blob/master/app/controllers/index.php#L315
