### ISSUE TITLE
Room Names in BigBlueButton

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-meeting#61]
Can we include the course name iin the room name?

**Comment by ferishili** [comment]
Isn't it better to pass course name (or additional data) to metadata field?

**Comment by lkiesow** [comment]
Any reason why that would be preferable? The room names could easily be used to identify courses with technical problems on BBB. Metadata would work as well but would be harder to use. Right now, the room name is based on the course event name (?), maning you end up in a room named something like:

- Session 01

I was thinking that having something like this would be nicer:

- Virus Studies A – Session 01

**Comment by ferishili** [comment]
The reason is to prevent redundant naming in UI. But I will find a workaround for that.

**Comment by lkiesow** [comment]
If it turns out to be problematic, metadata would already be helpful though.

**Comment by ferishili** [comment]
It is done. I have found the way for that, no worries.
