### ISSUE TITLE
Meetings-Aufzeichnungen und Opencast

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-meeting#62]
In Stud.IP sollen Aufzeichnungen für Räume immer deaktiviert sein bis das Opencast-Plugin dem Kurs hinzugefügt wurde. Die Aufzeichnungsansicht im Meetings-Plugin soll deaktiviert werden (Später Plugin-Einstellung).

Ist Opencast in dem Kurs aktiv soll ausgewählt werden können ob ein Meeting aufgezeichnet werden kann. Wird ein Raum für Aufzeichnungen freigegeben, so erscheint ein Hinweistext, dass die Veranstaltung grundsärtlich zunächst gecached wird und was aufgezeichnet wird (siehe unten). Basierend auf der Auswahl wird BigBlueButton beim anlegen der Räume „record=true/false“ übergeben.

Wenn „record=true“ wird immer ein zusätzliches Feld „opencast-series-id“ übergeben um zu identifizieren welche Serie in dem Kurs eingebunden wurde.

#### Hinweistext

Wird die Aufzeichnungsfunktion aktiviert, so wird das gesamte Meeting zunächst gecached und nach Beendigung des Meetings weiter verarbeitet. In der Verarbeitung werden alle Teile entfernt bei denen nicht die Aufzeichnung in BigBlueButton gestartet wurde. Eine kurze Zeit nach der Verarbeitung wird das Gesamtvideo vom Server entfernt.

**Comment by ferishili** [comment]
Is „opencast-series-id“ field an additional (create) parameter?
