### ISSUE TITLE
Lastprobleme

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/studip-meeting#70]
Das Meetingsplugin verursacht in seiner jetzigen Form wohl eine ziemlich hohe Last auf der Datenbank, das muss analysiert und behoben werden.

Im Verdacht steht die automatische Aktualisierung, vllt. sollte man die einfach weglassen und nur beim neuladen der Seite aktualisieren?

**Comment by tgloeggl** [comment]
Des weiteren muss das Verhalten, insbesondere die Ladezeit, beim Seitenaufruf überprüft werden wenn sich die Meetings in der Größenordnung 140 und darüber befinden!

**Comment by ferishili** [comment]
If I understand it correctly, it should call get the live info when room size is more than 140 participants. Is it correct?
