### ISSUE TITLE
Räume für Gruppen

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/studip-meeting#80]

**Comment by ferishili** [comment]
More details please. What needs to be done here?

**Comment by asudau** [comment]
I guess he means the Gruppen wich you can organise in Stud.IP in the section TeilnehmerInnen. If you create groups there you can use many resources in Stud.IP an say 'this is only for Group A'. That means only Group A can see an use that resource for example folders in the 'Dateibereich'.  
For Meeting Rooms this would mean i could assign a room to an existing participant group. Then only members of this group could see and join that meeting.

**Comment by asudau** [comment]
maybe you can test that with groupfolders to get an idea of what it migth look like and how it works  
![gruppenordner](https://user-images.githubusercontent.com/11834384/89388446-5559a200-d704-11ea-95fb-26dbb4dcceab.PNG)
