### ISSUE TITLE
tooltip 'Kamera nur für Moderatoren'

### ISSUE THREAD

**Issue by asudau** [virtUOS/studip-meeting#86]
Hier steht derzeit als Tooltip: Nur Moderatoren können ihre Webcam einschalten.  
  
Der Config Wert regelt aber die Funktion: Teilnehmer können Webcams anderer Teilnehmer sehen  
  
in der api steht dazu:  
webcamsOnlyForModerator = all webcams shared by viewers during this meeting to only appear for moderators  

Dh. Tooltip muss lauten: Nur Moderatoren können die freigegebenen Webcam-Bilder der Teilnehmenden sehen. Teilnehmende sehen nur sich selbst und Moderatoren

**Comment by ferishili** [comment]
PR #113 has taken care of this issue, please take a look at it.
It has been changed to "Nur Moderatoren können Webcams sehen" which provides the sufficient meaning as well!
