### ISSUE TITLE
BBB Aufnahme pro Meeting aktivieren

### ISSUE THREAD

**Issue by Janfred** [virtUOS/studip-meeting#87]
BigBlueButton zeichnet in Standardeinstellung alle Meetings auf, unabhängig ob im Meeting der "Aufnahme starten" Button gedrückt wird.
(siehe bigbluebutton/bigbluebutton#9202 )

Wenn im API-Call fürs Anlegen des Meetings 'recording' auf false gesetzt wird, findet auch die Aufnahme nicht statt.

Damit ließe sich DSGVO-Konformität herstellen ohne pauschal die Möglichkeit der Aufzeichnung mit BBB abzuschalten.

Hintergrund des Tickets: An der Uni Bremen ist das Plugin aktuell im Einsatz, in den BBB-Instanzen ist allerdings die Aufnahme abgeschaltet. Einige Veranstaltungen benötigen allerdings Veranstaltungsaufzeichnungen und müssen dafür dann auf andere Möglichkeiten ausweichen.

**Comment by basisbit** [comment]
Nur als Anmerkung / etwas Off-Topic: Das deaktivieren der Aufnahme alleine reicht nicht aus um DSGVO Konformität zu erreichen. Ihr solltet auf jeden Fall euch diese Seite durchlesen, um alle Konfigurationsstellen zu finden, welche ihr anpassen müsst oder in eurer Datenschutzerklärung beachten müsst:
https://docs.bigbluebutton.org/admin/privacy.html

**Comment by tgloeggl** [comment]
Recordings werden passend geschaltet beim erstellen und bearbeiten eines Raumes:

https://github.com/virtUOS/studip-meeting/blob/master/lib/Routes/Rooms/RoomAdd.php#L118
https://github.com/virtUOS/studip-meeting/blob/master/lib/Routes/Rooms/RoomEdit.php#L96
