### ISSUE TITLE
Meetingskonfiguration: Nutzer darauf hinweisen, Einstellungen zu speichern

### ISSUE THREAD

**Issue by Arnei** [virtUOS/studip-meeting#90]
Wenn man unter `Admins > System > Meetings` konfigurieren Änderungen am Server vornimmt (z.B. die URL ändert), muss man wenn man fertig ist unten auf der Seite nochmal `Einstellungen speichern`  drücken, damit die Änderungen wirksam werden. Dies ist einfach zu vergessen, da

1. Nach dem Drücken von `Server bearbeiten` die Änderungen angezeigt und auch gespeichert werden, nur nicht angewandt.
2. Der `Einstellungen speichern`-Button bei meiner Auflösung von 2560x1440 nicht direkt auf der Seite sichtbar ist, sondern erst gescrollt werden muss. Aus den Augen, aus dem Sinn.

Um dadurch entstehende Verwirrung zu vermeiden, sollte der Nutzer nach Bearbeiten der Serverkonfiguration darauf hingewiesen, dass diese noch mit `Einstellungen bestätigen` angewandt werden muss. Alternativ könnte möglicherweise der `Server bearbeiten`-Button diese Funktionalität direkt mit übernehmen.

(Version 2.4, Schema 24)

**Comment by tgloeggl** [comment]
Ist in der aktuellsten Version erledigt. Es gibt dort dann entsprechende Message-Boxen und Hinweise
