### ISSUE TITLE
Was macht "Administrationsrechte für alle Teilnehmenden"?

### ISSUE THREAD

**Issue by Arnei** [virtUOS/studip-meeting#91]
Beim Erstellen eines Raumes ist eine der zwei Grundeinstellungen `Administrationsrechte für alle Teilnehmenden`. Da das anscheinend so wichtig ist wäre es gut, wenn wie bei den zusätzlichen Funktionen eine Information dabeistünde die erklärt, was diese Einstellungen eigentlich tut. 

(Version 2.4, Schema 24)

**Comment by asudau** [comment]
Finde ich gut, wie wäre es mit:  
'Teilnehmende treten dem Meeting automatisch als Moderatoren bei und haben somit im Meeting dieselben Rechte wir Dozierende'

**Comment by lkiesow** [comment]
Ich würde alle Optionen in einen Block ziehen. Die Unterscheidung bei den Einstellungen verstehe ich nicht wirklich. 

Zudem würde ich einige Optionen umbenennen. Mein Vorschlag wäre:

![Screenshot from 2020-06-11 11-11-50](https://user-images.githubusercontent.com/1008395/84367497-9d60ba80-abd4-11ea-9e47-0f8bcc24252e.png)

Und, wie gesagt, dazu Grundeinstellungen und erweiterte Einstellungen zusammenfassen.

**Comment by asudau** [comment]
find ich gut 👍

**Comment by tgloeggl** [comment]
Optionen umbenennen geht klar, die Einstellungen werden aber nicht zusammengefasst, die hatten wir extra getrennt um Nutzer, die sich nicht tiefergehend mit dem Tool beschäftigen, nicht zu überfordern.

**Comment by asudau** [comment]
was mir auffällt, ist, dass die dauer und die MAx TN Zahl ja scon sehr zentral für die Nutzung sind. Wenn man die erweiterten Einstellugen nicht öffnet ist man zwingend darauf angewiesen, dass die sinnvoll befüllt sind und man nicht plötzlich aus der Sitzung fliegt weil man die zu Vorbereitugszwecken zu früh aufgemacht hat und dann die Zeit um ist. Oder nicht alle TN reinpassen. Kann man diese Felder entweder in die Grunddeinstellungen hochziehen oder in der Übersicht anzeigen??

**Comment by nimuelle** [comment]
schade das euch das nicht schon viel früher aufgefallen ist, dass hätte uns ne menge ärger und irritationen erspart...  ich hätte erstmal für alle vorhandenen meetings stump "unbegrenzt" eingetragen.

**Comment by ferishili** [comment]
The PR #113 has taken care of this issue which results according to this mockup: https://data.lkiesow.io/bbb/meeting-plugin-mockup-2.html
