### ISSUE TITLE
Einstellung zur Webcamfreigabe doppelt

### ISSUE THREAD

**Issue by Arnei** [virtUOS/studip-meeting#92]
Beim Erstellen eines Raumes kann man einstellen:
- Webcams nur für Moderatoren
- Teilnehmer Webcam deaktivieren

Laufen diese Einstellungen nicht auf dasselbe hinaus? In beiden Fällen können nur noch Moderatoren ihre Webcam freigeben.

(Version 2.4, Schema 24)

**Comment by asudau** [comment]
meiner Meinung nach ist hier die Bennenung der Option inklusive Tooltip falsch. Hatte mich mit Farbod mal ausführlich darüber unterhalten und wir hatten auch nochmal genauer in die api geguckt..
Siehe dazu auch hier https://github.com/virtUOS/studip-meeting/issues/86

**Comment by ferishili** [comment]
PR #113
