### ISSUE TITLE
Option für die Angabe weiterer Metadaten beim Erstellen eines Raumes mit aktivem Recording

### ISSUE THREAD

**Issue by Arnei** [virtUOS/studip-meeting#94]
Möglicherweise wäre es nett, wenn man beim Erstellen eines Meeting-Raumes mit aktivem Recording den Titel sowie den Vortragenden für das Recording einstellen könnte.

Momentan wird für den Titel eines Recordings der meetingName nach dem Schema "VeranstaltungsName - MeetingRaumName" genutzt. Es muss also jedes mal der Name des Raumes geändert werden, um den Titel zu ändern, was für Verwirrung sorgen könnte.

Die Möglichkeit einen Vortragenden zu definieren besteht soweit ich sehen kann gar nicht.

**Comment by asudau** [comment]
wäre es nicht denkbar das Datum der Aufnahme mit in den Titel zu nehmen (zumindest als Default wenn der Aufnahmetitel nicht manuell gesetzt wird) das behebt auch das Problem, dass man den Raum immer umbenennen muss. Und der Zeitpunkt einer Aufnahme ist ja häufig eine sehr relevante Info, wichtiger sogar, als z.B. der Titel des Raum

**Comment by lkiesow** [comment]
+1 für @asudau 
Das andere macht es noch komplizierter und wird auch dann schwierig zu handhaben wenn man nicht Opencast für die Aufzeichnungen verwendet

**Comment by Arnei** [comment]
Das Aufzeichnungsdatum ist im Opencast-Plugin doch schon recht prominent zu sehen, oder?
![Bildschirmfoto vom 2020-06-11 11-05-25](https://user-images.githubusercontent.com/14070005/84387867-f2f88f80-abf3-11ea-99cc-36c07ae87969.png)

**Comment by ferishili** [comment]
Is this issue still running?
A brief conclusion would be great to have here!

**Comment by asudau** [comment]
The initial problem was the naming of the recording which is automatically genereated like 'name of seminar + name of room' . This way every recording had the same title. The only way to change that would have been renaming the room.

The idea was that maybe the Dozent could set a title for the next recording. However taht way he would always have to remember to change the title for every new recording.

I suggested to add the date an Time of the recording to the title, as that would always be an individual identifier.
Seminar-title + room-name + date an time

Lars showed that in the opencast pugin the date an d time of recording are already attached to the recording-infos. However in case that students can download the recordings it would be very helpful for thmen, if the date and time are part of the title. So my suggestion would still be:

Seminar-title + room-name + date an time

btw: today there is the possibility for teachers to rename opencast recordings if they prefer that, but probably some are not willing to take the time

**Comment by ferishili** [comment]
Date and Time is provided in the title in case the room is going to be recorded, otherwise title won't have date and time!

**Comment by lkiesow** [comment]
@asudau 

> However in case that students can download the recordings it would be very helpful for thmen, if the date and time are part of the title.

How does adding the date to the title help if they download the files? Wouldn't having the date as part of the filename help more? They don't see the title after they download the files, do they?
