### ISSUE TITLE
DfnVC-Fehler beim Start

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-meeting#96]
Wenn ich in einen Testkurs mit Plugin gehe bekomme ich folgenden, etwas verzerrten Fehler:

![Screenshot from 2020-06-11 10-51-21](https://user-images.githubusercontent.com/1008395/84367808-09432300-abd5-11ea-8152-c15e2d7be140.png)

Der Fehler an sich mag mit den Einstellungen zutun haben. Das Aussehen des Fehlers ist aber so sicher nicht gewollt.

**Comment by tgloeggl** [comment]
Der Fehler tritt wieder auf - man sieht im Hintergrund auch gar keine Räume.
