### ISSUE TITLE
Aufzeichnungshinweis

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-meeting#97]
Es wird darauf hingewiesen, dass der Raum aufgezeichnet werden kann. Tatsächlich wird bei `recordings=true` aber immer zunächst aufgezeichnet. Eventuell wird die Aufzeichnung dann nur nicht veröffentlicht.

![Screenshot from 2020-06-09 13-53-47](https://user-images.githubusercontent.com/1008395/84368329-b5850980-abd5-11ea-918b-27a27eec4c09.png)

Das sollte also z.B. „Dieser Raum wird aufgezeichnet“ sein

**Comment by ferishili** [comment]
@lkiesow In PR #113:
It has been changed to "Bitte beachten Sie, dass dieser Raum aufgezeichnet wird!".
